import React,{useEffect,useMemo,useState} from 'react';

const API_BASE=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/$/,'');
const API=API_BASE+'/api';
const TOKEN_KEY='bidlens_session';
const fallbackTemplates=[
{id:'saas',name:'Enterprise SaaS / CRM',category:'Software / SaaS',prompt:'Need a 3-year SaaS procurement. Must support SSO/SAML, EU/India data residency, 99.9% SLA, implementation within 60 days, annual renewal cap <= 5%, and transparent pricing for 1,000 users. Prefer 60+ day payment terms and no auto-renewal surprise.'},
{id:'cloud',name:'Cloud / Data Platform',category:'Cloud & Data',prompt:'Evaluate a 3-year cloud/data platform procurement for 20 TB storage, 50M queries/month and 200 analysts. Compare technical fit, 3-year TCO, support, security, egress/export fees, annual uplift and minimum commitments.'},
{id:'cybersecurity',name:'Cybersecurity / MDR',category:'Security',prompt:'Evaluate a 3-year MDR procurement for 3,000 endpoints and 250 servers. Mandatory: 24x7 SOC, P1 response <=15 minutes, India data residency, ISO 27001 or SOC 2, and incident escalation.'},
{id:'hrpayroll',name:'HR / Payroll',category:'Business Applications',prompt:'Evaluate a 5-year HR/payroll procurement for 12,000 employees in India. Mandatory: Indian payroll, statutory support, SSO, audit logs, 99.9% availability and employee self-service.'},
{id:'hardware',name:'Hardware / Equipment',category:'Hardware / Logistics',prompt:'Evaluate a 3-year equipment procurement for 1,000 units. Compare unit price, total landed cost, shipping fees, volume discounts, payment terms, delivery lead time, warranty, specifications and service SLA.'},
{id:'professional-services',name:'Professional Services / SI',category:'Services',prompt:'Evaluate a professional-services procurement over 12 months. Compare implementation cost, day rates, staffing, milestones, delivery timeline, assumptions, change-request exposure, warranty/support, SLA and references.'},
{id:'negotiation',name:'Negotiation Copilot',category:'Commercial Strategy',prompt:'Analyze these vendor proposals as a procurement negotiation. Identify the top five negotiable commercial or contractual levers, evidence, buyer target, fallback position and vendor question.'}
];
function Score({value}){return <span className={value>=8?'good':value>=6?'mid':'bad'}>{Number(value).toFixed(1)}</span>}
function Status({s}){const label=s==='UNKNOWN'?'NEEDS CONFIRMATION':(s||'—');return <span className={'status '+String(label).toLowerCase().replaceAll(' ','-')}>{label}</span>}
function metricText(v,key){
 if(key==='financial') return `Unit ${v.unit_price==null?'—':'$'+Number(v.unit_price).toLocaleString()}/user/year · Annual ${v.annual_cost==null?'—':'$'+Number(v.annual_cost).toLocaleString()} · Payment ${v.payment_terms_days==null?'—':v.payment_terms_days+'d'} · Renewal ${v.renewal_increase_pct==null?'—':v.renewal_increase_pct+'%'}`;
 if(key==='technical') return `${(v.technical_capability||[]).slice(0,4).join(' · ')||'No technical evidence captured'} · SSO/SCIM: ${/sso|scim/i.test(v.security||'')?'evidenced':'confirm'}`;
 if(key==='reliability') return `Risk ${Number(v.risk_score).toFixed(1)}/10 · ${v.sla||'SLA not stated'} · Evidence ${Math.round((v.evidence_coverage||0)*100)}%`;
 return `Implementation ${v.implementation_days==null?'—':v.implementation_days+'d'} · ${(v.service_support||[]).slice(0,3).join(' · ')||'Support details not stated'}`;
}
function gateCell(c){
 if(!c) return <><Status s="NEEDS CONFIRMATION"/><small>No evidence captured.</small><em>Ask the vendor for explicit contractual evidence.</em></>;
 const normalized=c.status==='UNKNOWN'?'NEEDS CONFIRMATION':c.status;
 return <><Status s={normalized}/><small>{c.evidence||'No evidence captured.'}</small>{c.action&&normalized==='NEEDS CONFIRMATION'&&<em>{c.action}</em>}</>;
}
function LoginPage({onLogin}){
 const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e){e.preventDefault();setBusy(true);setError('');try{const r=await fetch(API+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})});const j=await r.json();if(!r.ok)throw Error(j.detail||'Invalid username or password');localStorage.setItem(TOKEN_KEY,j.token);onLogin(j.token)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <div className="auth-shell"><div className="auth-glow glow-a"></div><div className="auth-glow glow-b"></div><div className="auth-card"><div className="auth-brand"><span className="auth-mark">⚡</span><span>BIDLENS</span></div><div className="auth-kicker">PROCUREMENT INTELLIGENCE</div><h1>Enter the decision room.</h1><p>Secure access to vendor comparison, requirement gates and AI-powered procurement analysis.</p><form onSubmit={submit}><label>Username<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} placeholder="Enter username" required/></label><label>Password<input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter password" required/></label>{error&&<div className="auth-error">{error}</div>}<button className="auth-submit" disabled={busy}>{busy?<span className="run-progress"><i></i>Signing in…</span>:'Sign in →'}</button></form><div className="auth-foot">Authorized procurement workspace · Protected session</div></div></div>
}
function App(){
 const [token,setToken]=useState(()=>localStorage.getItem(TOKEN_KEY)||''),[requirements,setRequirements]=useState(''),[templates,setTemplates]=useState(fallbackTemplates),[selectedTemplate,setSelectedTemplate]=useState(''),[files,setFiles]=useState([]),[data,setData]=useState(null),[loading,setLoading]=useState(false),[scenario,setScenario]=useState(null),[redTeam,setRedTeam]=useState(null),[volume,setVolume]=useState(1000),[years,setYears]=useState(3),[error,setError]=useState(''),[progressTick,setProgressTick]=useState(0),[redLoading,setRedLoading]=useState(false),[booting,setBooting]=useState(true),[resources,setResources]=useState([]),[showResources,setShowResources]=useState(false),[resourceLoading,setResourceLoading]=useState(false);
 useEffect(()=>{if(!loading)return;const id=setInterval(()=>setProgressTick(x=>x+1),850);return()=>clearInterval(id)},[loading]);
 function logout(){localStorage.removeItem(TOKEN_KEY);setToken('');setData(null)}
 async function apiFetch(path,options={}){const headers=new Headers(options.headers||{});if(token)headers.set('Authorization',`Bearer ${token}`);const r=await fetch(API+path,{...options,headers});if(r.status===401){logout();throw Error('Your session expired. Please sign in again.')}return r}
 useEffect(()=>{if(!token){setBooting(false);return;}Promise.all([apiFetch('/templates').then(r=>r.json()).then(x=>setTemplates(x.templates||fallbackTemplates)),apiFetch('/latest').then(r=>r.json()).then(x=>x.result&&setData(x.result))]).catch(e=>{if(e.message) setError(e.message)}).finally(()=>setBooting(false))},[token]);
 async function openResources(){setShowResources(true);if(resources.length||resourceLoading)return;setResourceLoading(true);try{const r=await apiFetch('/resources');const j=await r.json();if(!r.ok)throw Error(j.detail||'Could not load resources');setResources(j.resources||[])}catch(e){setError(e.message)}finally{setResourceLoading(false)}}
 async function downloadResource(url,name){try{const r=await apiFetch(url);if(!r.ok)throw Error('Download failed');const blob=await r.blob();const objectUrl=URL.createObjectURL(blob);const a=document.createElement('a');a.href=objectUrl;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(objectUrl),1000)}catch(e){setError(e.message)}}
 const ranked=useMemo(()=>data?[...data.vendors].sort((a,b)=>b.fit_score-a.fit_score):[],[data]);
 const gateRows=useMemo(()=>{const seen=new Set();return (data?.requirement_checks||[]).filter(c=>{if(seen.has(c.requirement))return false;seen.add(c.requirement);return true}).map(c=>c.requirement)},[data]);
 function choose(id){setSelectedTemplate(id);const t=templates.find(x=>x.id===id);if(t)setRequirements(t.prompt)}
 function editRequirements(e){setRequirements(e.target.value);if(selectedTemplate)setSelectedTemplate('')}
 async function run(){setLoading(true);setError('');setScenario(null);setRedTeam(null);try{const fd=new FormData();fd.append('requirements',requirements);files.forEach(f=>fd.append('files',f));const r=await apiFetch('/analyze',{method:'POST',body:fd});const j=await r.json();if(!r.ok)throw Error(j.detail||'Analysis failed');setData(j.result)}catch(e){setError(e.message)}finally{setLoading(false)}}
 async function runScenario(){setError('');try{const r=await apiFetch('/scenario',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({volume_units_per_year:Number(volume),horizon_years:Number(years)})});const j=await r.json();if(r.ok)setScenario(j);else setError(j.detail||'Scenario failed')}catch(e){setError(e.message)}}
 async function runRedTeam(){if(!data)return;setRedLoading(true);setError('');try{const r=await apiFetch('/red-team',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({result:data})});const j=await r.json();if(r.ok)setRedTeam(j);else throw Error(j.detail||'Red-team analysis failed')}catch(e){setError(e.message)}finally{setRedLoading(false)}}
 async function reset(){if(!confirm('Clear the current analysis and uploaded files?'))return;try{await apiFetch('/reset',{method:'POST'});}catch(e){}setData(null);setScenario(null);setRedTeam(null);setFiles([]);setRequirements('');setSelectedTemplate('');setError('');const input=document.getElementById('files');if(input)input.value='';}
 if(!token)return <LoginPage onLogin={setToken}/>;
 if(booting)return <div className="boot-screen"><div className="boot-spinner"></div><b>Opening decision room…</b></div>;
 return <div className="app"><header><div><div className="eyebrow">PROCUREMENT INTELLIGENCE</div><h1>BidLens <span>⚡</span></h1><p>Don't compare proposals. <b>Stress-test the decision.</b></p></div><div className="head-actions"><div className="badge">GEMINI · AI AWARD ENGINE</div><button className="resources" onClick={openResources}>Resources</button><button className="reset" onClick={reset}>Clear analysis</button><button className="logout" onClick={logout}>Sign out</button></div></header>
 <main><section className="hero-grid"><div className="card input-card"><div className="step">01 · DEFINE THE ASK</div><label className="select-label">Procurement template (optional)<select value={selectedTemplate} onChange={e=>choose(e.target.value)}><option value="">Custom requirements</option>{templates.map(t=><option key={t.id} value={t.id}>{t.name} · {t.category}</option>)}</select></label><textarea placeholder="Add your custom requirements" value={requirements} onChange={editRequirements}/><div className="template-desc">Choose a template to populate the prompt, or write your own requirements. The prompt is the single source of truth for the buyer ask.</div><div className="drop" onClick={()=>document.getElementById('files').click()}><input id="files" type="file" multiple accept=".pdf,.docx,.txt,.md,.csv" onChange={e=>setFiles([...e.target.files])}/><div className="dropicon">＋</div><b>{files.length?`${files.length} vendor proposal(s) selected`:'Drop vendor proposals here'}</b><span>Upload 2+ vendor proposals · PDF · DOCX · TXT · MD · CSV</span></div><button onClick={run} disabled={loading||files.length<2||!requirements.trim()}>{loading?<span className="run-progress"><i></i>{['Reading proposals…','Extracting vendor facts…','Checking requirement gates…','Scoring vendors…','Finalizing recommendation…'][Math.min(4,progressTick%5)]}</span>:'Run award analysis →'}</button>{error&&<div className="error">{error}</div>}</div>
 <div className="card insight-card"><div className="step">02 · LIVE DECISION ROOM</div>{data?<><div className="winner"><span>{String(data.recommendation).startsWith('HOLD')?'DECISION STATUS':'RECOMMENDED'}</span><strong>{data.recommendation}</strong><em>{String(data.recommendation).startsWith('HOLD')?'—':Number(data.award_score).toFixed(1)+'/10'}</em></div><p className="rationale">{data.rationale}</p><div className="mini"><div><span>CONFIDENCE</span><b>{Math.round(data.overall_confidence*100)}%</b></div><div><span>GAPS / CONTRADICTIONS</span><b>{(data.contradictions||[]).length}</b></div><div><span>VENDORS</span><b>{data.vendors.length}</b></div></div><div className="red-team-cta"><button onClick={runRedTeam} disabled={redLoading}>{redLoading?<span className="run-progress"><i></i>Challenging the decision…</span>:'🛡️ Red-team the recommendation'}</button><span>AI adversarial check: try to disprove the winner using only proposal evidence.</span></div></>:<div className="empty">Choose a template or write your ask, upload 2+ proposals and create the decision room.</div>}</div></section>
 {data&&<>
 <section className="section"><div className="section-title"><h2>Vendor battleground</h2><span>Evidence-backed scorecards</span></div><div className="category-grid">{[["financial","Financial metrics"],["technical","Technical capability"],["reliability","Vendor reliability"],["service","Service & support"]].map(([key,title])=><div className="metric-card" key={key}><b>{title}</b>{ranked.map(v=><div className="metric-row" key={v.name}><strong>{v.name}</strong><span>{metricText(v,key)}</span></div>)}</div>)}</div><div className="table-wrap"><table><thead><tr><th>Vendor</th><th>Fit</th><th>Commercial</th><th>Risk</th><th>Unit</th><th>Annual</th><th>Shipping</th><th>Payment</th><th>Volume discount</th><th>Renewal</th><th>Evidence</th></tr></thead><tbody>{ranked.map(v=><tr key={v.name}><td><b>{v.name}</b></td><td><Score value={v.fit_score}/></td><td><Score value={v.commercial_score}/></td><td><Score value={10-v.risk_score}/></td><td>{v.unit_price==null?'—':v.unit_price}</td><td>{v.annual_cost==null?'—':`$${Number(v.annual_cost).toLocaleString()}`}</td><td>{v.shipping_fees==null?'—':`$${Number(v.shipping_fees).toLocaleString()}`}</td><td>{v.payment_terms_days==null?'—':`${v.payment_terms_days}d`}</td><td>{v.volume_discount||'Not stated'}</td><td>{v.renewal_increase_pct==null?'—':`${v.renewal_increase_pct}%`}</td><td>{Math.round((v.evidence_coverage||0)*100)}%</td></tr>)}</tbody></table></div></section>
 <section className="section card"><div className="section-title"><h2>Requirement gate</h2><span>PASS · FAIL · NEEDS CONFIRMATION</span></div><div className="gate-wrap"><table className="gate-table"><thead><tr><th>Requirement / key point</th>{data.vendors.map(v=><th key={v.name}>{v.name}</th>)}</tr></thead><tbody>{gateRows.map(req=><tr key={req}><td><b>{req}</b></td>{data.vendors.map(v=><td key={v.name}>{gateCell((data.requirement_checks||[]).find(c=>c.vendor===v.name&&c.requirement===req))}</td>)}</tr>)}</tbody></table></div></section>
 {redTeam&&<section className="section card red-team"><div className="section-title"><h2>🛡️ AI Red-Team Challenge</h2><span>{redTeam.verdict||'Decision challenge'}</span></div><p className="rationale">{redTeam.summary}</p><div className="red-grid">{(redTeam.challenges||[]).map((x,i)=><div className="metric-card" key={i}><b>{x.title||`Challenge ${i+1}`}</b><span>{x.evidence||''}</span><small>{x.impact||''}</small></div>)}</div></section>}
 <section className="two-col"><div className="card"><div className="section-title"><h2>⚠ Risks humans miss</h2></div>{data.vendors.map(v=><div className="risk-block" key={v.name}><b>{v.name}</b>{v.risks.length?v.risks.map((r,i)=><div className="risk" key={i}>⚠ {r}</div>):<div className="safe">No major risk surfaced</div>}</div>)}</div><div className="card"><div className="section-title"><h2>🤝 Negotiation Copilot</h2></div>{(data.negotiation||[]).length?(data.negotiation.slice(0,5).map((n,i)=><div className="neg" key={i}><b>{n.vendor||'Vendor'}</b><div>{n.lever||n.point||JSON.stringify(n)}</div><small>{n.vendor_question||n.evidence||''}</small></div>)):<div className="safe">No negotiation levers returned. Try the Negotiation Copilot template.</div>}</div></section>
 <section className="card scenario"><div className="section-title"><h2>03 · Counterfactual award simulator</h2><span>Stress-test price, scale and time horizon.</span></div><div className="controls"><label>Units/year<input type="number" min="1" value={volume} onChange={e=>setVolume(e.target.value)}/></label><label>Horizon<input type="number" min="1" value={years} onChange={e=>setYears(e.target.value)}/></label><button onClick={runScenario}>Stress-test →</button></div>{scenario&&<><div className={'scenario-winner '+(scenario.decision_change?'flip':'')}>{scenario.decision_change?'⚡ DECISION CHANGED — ':''}At <b>{Number(volume).toLocaleString()}</b> units/year for <b>{years} years</b>, eligible winner: <strong>{scenario.winner}</strong></div><div className="scenario-grid">{scenario.vendors.map(v=><div className={'scenario-item '+(v.eligible?'eligible':'ineligible')} key={v.name}><div className="scenario-head"><b>{v.name}</b><span className={'eligibility '+(v.eligible?'yes':'no')}>{v.eligible?'ELIGIBLE':'INELIGIBLE'}</span></div><span>${Number(v.tco).toLocaleString()} TCO</span><span>Scenario score {Number(v.award_score).toFixed(1)}</span><small>{v.eligibility_reason||''}</small></div>)}</div><p className="scenario-explain">{scenario.explanation}</p></>}</section>
 </>}
 </main>{showResources&&<div className="modal-backdrop" onClick={()=>setShowResources(false)}><div className="resource-modal" onClick={e=>e.stopPropagation()}><div className="resource-head"><div><div className="eyebrow">JUDGE RESOURCES</div><h2>Sample proposal library</h2><p>Download ready-to-run proposal sets for the demo. Requirements files are intentionally excluded because the buyer ask now comes from the selected template or custom prompt.</p></div><button className="modal-close" onClick={()=>setShowResources(false)}>×</button></div><div className="resource-toolbar"><span>{resourceLoading?'Loading sample packs…':'Sample packs'} </span><button onClick={()=>downloadResource('/resources/download-all','bidlens-sample-proposals.zip')}>Download all proposals</button></div>{resourceLoading?<div className="resource-loading">Preparing resources…</div>:<div className="resource-list">{resources.map(group=><div className="resource-group" key={group.id}><div><b>{group.name}</b><p>{group.description}</p></div><div className="resource-files">{group.files.map(file=><button className="file-chip" key={file.name} onClick={()=>downloadResource(file.download.replace(/^\/api/,''),file.name)}>↧ {file.name}</button>)}</div></div>)}</div>}</div></div>}<footer>BidLens · Gemini-powered procurement intelligence · AI understands evidence; deterministic logic protects the decision.</footer></div>
}
export default App;
